version: "3.9"

services:
  db:
    container_name: mysql_db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atc
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=root"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - atc-network

  train:
    build:
      context: .
      dockerfile: Dockerfile.train_model
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - model_data:/train/model_data
    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOSTS_STRICT=0
    command: ["sh", "-c", "wait && python train_model.py"]
    networks:
      - atc-network

  app:
    container_name: atc_app
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - db
      - train
    ports:
      - "5000:5000"
    volumes:
      - model_data:/app/model_data
    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOSTS_STRICT=0
    command: ["sh", "-c", "wait && python main.py"]
    networks:
      - atc-network

networks:
  atc-network:
    driver: bridge

volumes:
  model_data:
